  
name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.SECRET_KEY }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/London-Gaming-Network/projects/1'
        column_name: 'Needs Review'
